//:include html/html.js

q.html.UVCommonValues = {};

q.html.UVCommonValues.keys = [
  "version",
  "page",
  "category",
  "subcategory",
  "user",
  "name",
  "username",
  "user_id",
  "email",
  "language",
  "returning",
  "facebook_id",
  "twitter_id",
  "listing",
  "items",
  "id",
  "sku",
  "url",
  "manufacturer",
  "color",
  "currency",
  "unit_price",
  "unit_sale_price",
  "basket",
  "subtotal",
  "subtotal_include_tax",
  "tax",
  "shipping_cost",
  "total",
  "line_items",
  "product",
  "sku_code",
  "quantity",
  "environment",
  "variation",
  "revision",
  "age",
  "gender",
  "first_order",
  "registered_today",
  "registered_in_current_session",
  "registration_date",
  "last_order_date",
  "last_transaction_payment_type"];

q.html.UVCommonValues.values = [
  "",
  true,
  false,
  "true",
  "false",
  "GBP",
  "USD",
  "production"
];